---

- name: Add WireGuard PPA
  apt_repository:
    repo: ppa:wireguard/wireguard
  when: ansible_distribution == 'Ubuntu'

- name: Install Linux kernel headers
  apt:
    name: linux-headers-amd64
  when: ansible_distribution == 'Debian'

- name: Install WireGuard (Ubuntu)
  apt:
    name: wireguard
  when: ansible_distribution == 'Ubuntu'

- name: Install WireGuard (Debian)
  apt:
    name: wireguard
    default_release: buster-backports
  when: ansible_distribution == 'Debian'
